/**
 * La auditoría de la revisión como planilla de Excel (D-142, D-143).
 *
 * Cinco hojas, cada una una tabla con filtros: las fichas, los revisores, las
 * sesiones de tiempo una a una, la edición sección a sección y el historial.
 * Salen de la misma `Auditoria` que pinta la pantalla, así que dicen lo mismo:
 * quien la descarga para filtrarla está comprobando la pantalla con otras
 * herramientas, y dos cuentas distintas lo dejarían sin saber cuál creer.
 *
 * Los tiempos van en minutos con un decimal y los porcentajes como números de
 * 0 a 100: es lo que se filtra y se suma sin convertir nada.
 */
import { NOMBRE_DE_MODULO } from '@/app/(frontend)/admin-panel/modulos'
import type { Auditoria } from './auditoria'
import { estadoEnPalabras } from './revision'
import type { HojaDePlanilla } from './planilla'

const siNo = (valor: boolean) => (valor ? 'Sí' : 'No')
const modulo = (slug: string) => NOMBRE_DE_MODULO[slug] ?? slug

export function hojasDeLaAuditoria(auditoria: Auditoria): HojaDePlanilla[] {
  return [
    {
      nombre: 'Contenidos',
      columnas: [
        { titulo: 'Módulo', tipo: 'texto', ancho: 22 },
        { titulo: 'Ficha', tipo: 'texto', ancho: 40 },
        { titulo: 'ID', tipo: 'entero', ancho: 8 },
        { titulo: 'Estado', tipo: 'texto', ancho: 20 },
        { titulo: 'Origen', tipo: 'texto', ancho: 16 },
        { titulo: 'Libro', tipo: 'texto', ancho: 30 },
        { titulo: 'Capítulo', tipo: 'texto', ancho: 12 },
        { titulo: 'Páginas', tipo: 'texto', ancho: 12 },
        { titulo: 'Lote', tipo: 'texto', ancho: 18 },
        { titulo: 'Modelo', tipo: 'texto', ancho: 18 },
        { titulo: 'Asignada a', tipo: 'texto' },
        { titulo: 'Validada por', tipo: 'texto' },
        { titulo: 'Validada el', tipo: 'fecha' },
        { titulo: 'Publicada el', tipo: 'fecha' },
        { titulo: '% editado', tipo: 'decimal' },
        { titulo: 'Palabras originales', tipo: 'entero' },
        { titulo: 'Palabras actuales', tipo: 'entero' },
        { titulo: 'Palabras quitadas o reemplazadas', tipo: 'entero' },
        { titulo: 'Palabras nuevas', tipo: 'entero' },
        { titulo: 'Minutos activos (todos)', tipo: 'decimal' },
        { titulo: 'Minutos abiertos (todos)', tipo: 'decimal' },
        { titulo: 'Minutos activos del validador', tipo: 'decimal' },
        { titulo: 'Palabras por minuto del validador', tipo: 'decimal' },
        { titulo: 'Secciones revisadas', tipo: 'entero' },
        { titulo: 'Secciones con contenido', tipo: 'entero' },
        { titulo: 'Validación señalada', tipo: 'texto', ancho: 10 },
        { titulo: 'Por qué se señaló', tipo: 'texto', ancho: 50 },
        { titulo: 'Nota del revisor', tipo: 'texto', ancho: 40 },
        { titulo: 'Veces devuelta', tipo: 'entero' },
        { titulo: 'Publicada sin validar', tipo: 'texto', ancho: 10 },
        { titulo: 'Última edición', tipo: 'fecha' },
        { titulo: 'En revisión desde', tipo: 'fecha' },
      ],
      filas: auditoria.contenidos.map((c) => [
        modulo(c.coleccion),
        c.titulo,
        Number(c.documentoId),
        estadoEnPalabras(c.estado),
        c.origen,
        c.libro,
        c.capitulo,
        c.paginas,
        c.lote,
        c.modelo,
        c.asignada || 'Sin asignar',
        c.validador,
        c.validadaEn,
        c.publicadaEn,
        c.porcentaje,
        c.palabrasOriginales,
        c.palabrasActuales,
        c.palabrasQuitadas,
        c.palabrasNuevas,
        c.minutosActivos,
        c.minutosAbiertos,
        c.minutosActivosDelValidador,
        c.ritmoDelValidador,
        c.seccionesRevisadas,
        c.seccionesConContenido,
        c.validadaEn ? siNo(c.senalada) : '',
        c.motivos,
        c.nota,
        c.devoluciones,
        siNo(c.publicadaSinValidar),
        c.ultimaEdicion,
        c.registradaEn,
      ]),
    },
    {
      nombre: 'Revisores',
      columnas: [
        { titulo: 'Revisor', tipo: 'texto', ancho: 28 },
        { titulo: 'Correo', tipo: 'texto', ancho: 30 },
        { titulo: 'Rol', tipo: 'texto', ancho: 12 },
        { titulo: 'Fichas asignadas', tipo: 'entero' },
        { titulo: 'Asignadas sin terminar', tipo: 'entero' },
        { titulo: 'Fichas validadas', tipo: 'entero' },
        { titulo: 'Validaciones señaladas', tipo: 'entero' },
        { titulo: 'Validaciones devueltas', tipo: 'entero' },
        { titulo: 'Fichas abiertas', tipo: 'entero' },
        { titulo: 'Minutos activos', tipo: 'decimal' },
        { titulo: 'Minutos abiertos', tipo: 'decimal' },
        { titulo: 'Minutos activos por ficha validada', tipo: 'decimal' },
        { titulo: 'Palabras por minuto (media)', tipo: 'decimal' },
        { titulo: '% editado en lo validado (media)', tipo: 'decimal' },
        { titulo: 'Última actividad', tipo: 'fecha' },
      ],
      filas: auditoria.revisores.map((r) => [
        r.nombre,
        r.correo,
        r.rol === 'admin' ? 'Administrador' : r.rol === 'editor' ? 'Editor' : r.rol,
        r.asignadas,
        r.pendientes,
        r.validadas,
        r.senaladas,
        r.devueltas,
        r.fichasAbiertas,
        r.minutosActivos,
        r.minutosAbiertos,
        r.minutosPorValidada,
        r.ritmoMedio,
        r.porcentajeMedio,
        r.ultimaActividad,
      ]),
    },
    {
      nombre: 'Sesiones',
      columnas: [
        { titulo: 'Revisor', tipo: 'texto', ancho: 28 },
        { titulo: 'Módulo', tipo: 'texto', ancho: 22 },
        { titulo: 'Ficha', tipo: 'texto', ancho: 40 },
        { titulo: 'ID', tipo: 'entero', ancho: 8 },
        { titulo: 'Inicio', tipo: 'fecha' },
        { titulo: 'Último latido', tipo: 'fecha' },
        { titulo: 'Minutos abiertos', tipo: 'decimal' },
        { titulo: 'Minutos activos', tipo: 'decimal' },
        { titulo: 'Ediciones', tipo: 'entero' },
        { titulo: 'Guardados', tipo: 'entero' },
        { titulo: 'Segundos activos por sección', tipo: 'texto', ancho: 60 },
      ],
      filas: auditoria.sesiones.map((s) => [
        s.revisor,
        modulo(s.coleccion),
        s.titulo,
        Number(s.documentoId),
        s.inicio,
        s.ultimoLatido,
        s.minutosAbiertos,
        s.minutosActivos,
        s.ediciones,
        s.guardados,
        s.secciones,
      ]),
    },
    {
      nombre: 'Secciones',
      columnas: [
        { titulo: 'Módulo', tipo: 'texto', ancho: 22 },
        { titulo: 'Ficha', tipo: 'texto', ancho: 40 },
        { titulo: 'ID', tipo: 'entero', ancho: 8 },
        { titulo: 'Sección', tipo: 'texto', ancho: 22 },
        { titulo: 'Palabras originales', tipo: 'entero' },
        { titulo: 'Palabras actuales', tipo: 'entero' },
        { titulo: '% editado', tipo: 'decimal' },
      ],
      filas: auditoria.contenidos.flatMap((c) =>
        c.porSeccion.map((s) => [
          modulo(c.coleccion),
          c.titulo,
          Number(c.documentoId),
          s.seccion,
          s.original,
          s.actual,
          s.porcentaje,
        ]),
      ),
    },
    {
      nombre: 'Historial',
      columnas: [
        { titulo: 'Fecha', tipo: 'fecha' },
        { titulo: 'Módulo', tipo: 'texto', ancho: 22 },
        { titulo: 'Ficha', tipo: 'texto', ancho: 40 },
        { titulo: 'ID', tipo: 'entero', ancho: 8 },
        { titulo: 'Qué pasó', tipo: 'texto', ancho: 26 },
        { titulo: 'Quién', tipo: 'texto', ancho: 28 },
        { titulo: 'Detalle', tipo: 'texto', ancho: 60 },
        { titulo: '% editado en ese momento', tipo: 'decimal' },
        { titulo: 'Minutos activos del revisor', tipo: 'decimal' },
      ],
      filas: auditoria.historial.map((h) => [
        h.fecha,
        modulo(h.coleccion),
        h.titulo,
        Number(h.documentoId),
        h.accion,
        h.usuario,
        h.detalle,
        h.porcentaje,
        h.minutosActivos,
      ]),
    },
  ]
}
