/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    segmentos: Segmento;
    medios: Medio;
    'modelos-3d': Modelos3D;
    patologias: Patologia;
    maniobras: Maniobra;
    'casos-ao': CasosAo;
    cirugias: Cirugia;
    'estudios-ia': EstudiosIa;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    segmentos: SegmentosSelect<false> | SegmentosSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    'modelos-3d': Modelos3DSelect<false> | Modelos3DSelect<true>;
    patologias: PatologiasSelect<false> | PatologiasSelect<true>;
    maniobras: ManiobrasSelect<false> | ManiobrasSelect<true>;
    'casos-ao': CasosAoSelect<false> | CasosAoSelect<true>;
    cirugias: CirugiasSelect<false> | CirugiasSelect<true>;
    'estudios-ia': EstudiosIaSelect<false> | EstudiosIaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  /**
   * El editor redacta y publica contenido; no crea ni activa cuentas.
   */
  rol: 'admin' | 'editor' | 'lector';
  /**
   * Mientras esté desmarcada, la cuenta no puede ver nada de la plataforma.
   */
  activo?: boolean | null;
  institucion?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segmentos".
 */
export interface Segmento {
  id: number;
  nombre: string;
  orden?: number | null;
  /**
   * Recuadro sensible del mapa. Se ajusta visualmente y se guarda aquí.
   */
  zonaMapa?: {
    x?: number | null;
    y?: number | null;
    ancho?: number | null;
    alto?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  /**
   * Qué se ve en la imagen. Sin esto la plataforma no es accesible.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    ancho?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-3d".
 */
export interface Modelos3D {
  id: number;
  nombre: string;
  origen: 'tc' | 'rm' | 'sintetico';
  /**
   * Los metadatos DICOM guardan nombre, identificador y fecha de nacimiento aunque la imagen se vea anónima. Ver Q-007 de la bitácora.
   */
  anonimizado?: boolean | null;
  /**
   * Referencia de rendimiento. El objetivo para navegador va de 50.000 a 150.000.
   */
  triangulos?: number | null;
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Fichas por segmento. Cada una termina en manejo y rehabilitación.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patologias".
 */
export interface Patologia {
  id: number;
  nombre: string;
  subtitulo?: string | null;
  segmento: number | Segmento;
  codigo?: string | null;
  tipo?: ('trauma' | 'ortopedia') | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  definicion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  mecanismo?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  clasificacion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  evaluacion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  manejo?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  rehabilitacion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  fases?:
    | {
        cuando: string;
        titulo: string;
        contenido: string;
        criterio?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Maniobras por segmento, con técnica, interpretación y video.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maniobras".
 */
export interface Maniobra {
  id: number;
  nombre: string;
  segmento: number | Segmento;
  evalua: string;
  tecnica: string;
  positivo: string;
  nota?: string | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * La secuencia quirúrgica con el principio AO que sustenta cada gesto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos-ao".
 */
export interface CasosAo {
  id: number;
  titulo: string;
  codigo?: string | null;
  procedimiento?: string | null;
  pasos?:
    | {
        titulo: string;
        descripcion: string;
        principio: string;
        nota?: string | null;
        modelo?: (number | null) | Modelos3D;
        id?: string | null;
      }[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Guion quirúrgico paso a paso con instrumental y fuerza aplicada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cirugias".
 */
export interface Cirugia {
  id: number;
  nombre: string;
  codigo?: string | null;
  resumen?: string | null;
  pasos?:
    | {
        titulo: string;
        descripcion: string;
        instrumento: string;
        fuerzaMinima: number;
        fuerzaMaxima: number;
        exito: string;
        insuficiente: string;
        excesivo: string;
        riesgo?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Casos precargados. No hay modelo de inferencia: los resultados están escritos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estudios-ia".
 */
export interface EstudiosIa {
  id: number;
  nombre: string;
  codigo?: string | null;
  confianza?: number | null;
  hallazgos?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  opciones?:
    | {
        titulo: string;
        frecuente?: boolean | null;
        aFavor?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        enContra?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Posición desde la que se ve el modelo al abrir la ficha. Se ajusta en el visor y se guarda aquí.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'segmentos';
        value: number | Segmento;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'modelos-3d';
        value: number | Modelos3D;
      } | null)
    | ({
        relationTo: 'patologias';
        value: number | Patologia;
      } | null)
    | ({
        relationTo: 'maniobras';
        value: number | Maniobra;
      } | null)
    | ({
        relationTo: 'casos-ao';
        value: number | CasosAo;
      } | null)
    | ({
        relationTo: 'cirugias';
        value: number | Cirugia;
      } | null)
    | ({
        relationTo: 'estudios-ia';
        value: number | EstudiosIa;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  activo?: T;
  institucion?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segmentos_select".
 */
export interface SegmentosSelect<T extends boolean = true> {
  nombre?: T;
  orden?: T;
  zonaMapa?:
    | T
    | {
        x?: T;
        y?: T;
        ancho?: T;
        alto?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        ancho?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-3d_select".
 */
export interface Modelos3DSelect<T extends boolean = true> {
  nombre?: T;
  origen?: T;
  anonimizado?: T;
  triangulos?: T;
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patologias_select".
 */
export interface PatologiasSelect<T extends boolean = true> {
  nombre?: T;
  subtitulo?: T;
  segmento?: T;
  codigo?: T;
  tipo?: T;
  definicion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  mecanismo?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  clasificacion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  evaluacion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  manejo?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  rehabilitacion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  fases?:
    | T
    | {
        cuando?: T;
        titulo?: T;
        contenido?: T;
        criterio?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maniobras_select".
 */
export interface ManiobrasSelect<T extends boolean = true> {
  nombre?: T;
  segmento?: T;
  evalua?: T;
  tecnica?: T;
  positivo?: T;
  nota?: T;
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos-ao_select".
 */
export interface CasosAoSelect<T extends boolean = true> {
  titulo?: T;
  codigo?: T;
  procedimiento?: T;
  pasos?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        principio?: T;
        nota?: T;
        modelo?: T;
        id?: T;
      };
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cirugias_select".
 */
export interface CirugiasSelect<T extends boolean = true> {
  nombre?: T;
  codigo?: T;
  resumen?: T;
  pasos?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        instrumento?: T;
        fuerzaMinima?: T;
        fuerzaMaxima?: T;
        exito?: T;
        insuficiente?: T;
        excesivo?: T;
        riesgo?: T;
        id?: T;
      };
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estudios-ia_select".
 */
export interface EstudiosIaSelect<T extends boolean = true> {
  nombre?: T;
  codigo?: T;
  confianza?: T;
  hallazgos?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  opciones?:
    | T
    | {
        titulo?: T;
        frecuente?: T;
        aFavor?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        enContra?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        id?: T;
      };
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}