/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    segmentos: Segmento;
    medios: Medio;
    'modelos-3d': Modelos3D;
    'instancias-atlas': InstanciasAtlas;
    'huesos-ao': HuesosAo;
    'clasificaciones-ao': ClasificacionesAo;
    'tecnicas-quirurgicas': TecnicasQuirurgica;
    'fases-quirurgicas': FasesQuirurgica;
    instrumental: Instrumental;
    patologias: Patologia;
    maniobras: Maniobra;
    'casos-ao': CasosAo;
    cirugias: Cirugia;
    'estudios-ia': EstudiosIa;
    comentarios: Comentario;
    actividad: Actividad;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    segmentos: SegmentosSelect<false> | SegmentosSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    'modelos-3d': Modelos3DSelect<false> | Modelos3DSelect<true>;
    'instancias-atlas': InstanciasAtlasSelect<false> | InstanciasAtlasSelect<true>;
    'huesos-ao': HuesosAoSelect<false> | HuesosAoSelect<true>;
    'clasificaciones-ao': ClasificacionesAoSelect<false> | ClasificacionesAoSelect<true>;
    'tecnicas-quirurgicas': TecnicasQuirurgicasSelect<false> | TecnicasQuirurgicasSelect<true>;
    'fases-quirurgicas': FasesQuirurgicasSelect<false> | FasesQuirurgicasSelect<true>;
    instrumental: InstrumentalSelect<false> | InstrumentalSelect<true>;
    patologias: PatologiasSelect<false> | PatologiasSelect<true>;
    maniobras: ManiobrasSelect<false> | ManiobrasSelect<true>;
    'casos-ao': CasosAoSelect<false> | CasosAoSelect<true>;
    cirugias: CirugiasSelect<false> | CirugiasSelect<true>;
    'estudios-ia': EstudiosIaSelect<false> | EstudiosIaSelect<true>;
    comentarios: ComentariosSelect<false> | ComentariosSelect<true>;
    actividad: ActividadSelect<false> | ActividadSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  /**
   * El editor redacta y publica contenido; no crea ni activa cuentas.
   */
  rol: 'admin' | 'editor' | 'lector';
  /**
   * Mientras esté desmarcada, la cuenta no puede ver nada de la plataforma.
   */
  activo?: boolean | null;
  institucion?: string | null;
  /**
   * Sin marcar ninguno, ve los cinco. Marque solo para restringir.
   */
  modulosVisibles?: ('patologias' | 'maniobras' | 'casos-ao' | 'cirugias' | 'estudios-ia')[] | null;
  /**
   * Solo tiene efecto sobre un editor: un lector no escribe nada y un administrador lo escribe todo.
   */
  modulosEditables?: ('patologias' | 'maniobras' | 'casos-ao' | 'cirugias' | 'estudios-ia')[] | null;
  /**
   * Lo anota la plataforma en cada inicio de sesión.
   */
  ultimoAcceso?: string | null;
  /**
   * Visible solo para administradores. Por ejemplo, quién pidió esta cuenta.
   */
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segmentos".
 */
export interface Segmento {
  id: number;
  nombre: string;
  orden?: number | null;
  /**
   * Recuadro sensible del mapa. Se ajusta visualmente y se guarda aquí.
   */
  zonaMapa?: {
    x?: number | null;
    y?: number | null;
    ancho?: number | null;
    alto?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  /**
   * Qué se ve en la imagen. Sin esto la plataforma no es accesible.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    ancho?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-3d".
 */
export interface Modelos3D {
  id: number;
  nombre: string;
  origen: 'tc' | 'rm' | 'sintetico';
  /**
   * Los metadatos DICOM guardan nombre, identificador y fecha de nacimiento aunque la imagen se vea anónima. Ver Q-007 de la bitácora.
   */
  anonimizado?: boolean | null;
  /**
   * Referencia de rendimiento. El objetivo para navegador va de 50.000 a 150.000.
   */
  triangulos?: number | null;
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Recortes del atlas listos para insertar en una ficha.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instancias-atlas".
 */
export interface InstanciasAtlas {
  id: number;
  nombre: string;
  /**
   * Qué muestra y en qué ficha se piensa usar.
   */
  descripcion?: string | null;
  /**
   * Ordena las preparaciones junto al resto del contenido.
   */
  segmento?: (number | null) | Segmento;
  /**
   * Lo calcula la plataforma al guardar.
   */
  numeroDePiezas?: number | null;
  /**
   * Lo escribe el taller del atlas. No se edita a mano.
   */
  contenido:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Con qué preparación del atlas se creó. Si el atlas se regenera, sirve para avisar de las piezas que ya no existan.
   */
  atlasVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hueso y tercio, con el número que le da la AO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "huesos-ao".
 */
export interface HuesosAo {
  id: number;
  nombre: string;
  /**
   * El primero del código. «42» para la diáfisis de la tibia.
   */
  codigo?: string | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tipo y grupo del trazo de fractura, sin el hueso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clasificaciones-ao".
 */
export interface ClasificacionesAo {
  id: number;
  /**
   * «A2», «B1», «C3». Sin el número del hueso.
   */
  codigo: string;
  nombre: string;
  /**
   * Los tres tipos de la AO. Esta lista sí es cerrada: es la propia clasificación.
   */
  tipo?: ('A' | 'B' | 'C') | null;
  descripcion?: string | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clavo endomedular, placa, tornillos, fijador externo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tecnicas-quirurgicas".
 */
export interface TecnicasQuirurgica {
  id: number;
  nombre: string;
  descripcion?: string | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Abordaje, reducción, fijación, cierre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fases-quirurgicas".
 */
export interface FasesQuirurgica {
  id: number;
  nombre: string;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * La bandeja de la consola. Cada paso declara cuál es el correcto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instrumental".
 */
export interface Instrumental {
  id: number;
  nombre: string;
  icono?:
    | (
        | 'generico'
        | 'bisturi'
        | 'separador'
        | 'pinza'
        | 'tijera'
        | 'punzon'
        | 'guia'
        | 'fresa'
        | 'martillo'
        | 'atornillador'
        | 'aguja'
      )
    | null;
  descripcion?: string | null;
  /**
   * Solo para ordenar el catálogo. La bandeja de un caso la forman los instrumentos que sus pasos declaran, no esta lista.
   */
  tecnicas?: (number | TecnicasQuirurgica)[] | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fichas por segmento. Cada una termina en manejo y rehabilitación.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patologias".
 */
export interface Patologia {
  id: number;
  nombre: string;
  subtitulo?: string | null;
  segmento: number | Segmento;
  codigo?: string | null;
  tipo?: ('trauma' | 'ortopedia') | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  definicion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  mecanismo?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  clasificacion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  evaluacion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  manejo?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  rehabilitacion?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  fases?:
    | {
        cuando: string;
        titulo: string;
        contenido: string;
        criterio?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Maniobras por segmento, con técnica, interpretación y video.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maniobras".
 */
export interface Maniobra {
  id: number;
  nombre: string;
  segmento: number | Segmento;
  evalua: string;
  tecnica: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  positivo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  nota?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * La secuencia quirúrgica con el principio AO que sustenta cada gesto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos-ao".
 */
export interface CasosAo {
  id: number;
  titulo: string;
  codigo?: string | null;
  procedimiento?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pasos?:
    | {
        titulo: string;
        descripcion: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        principio: string;
        nota?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        modelo?: (number | null) | Modelos3D;
        id?: string | null;
      }[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Caso quirúrgico con su modelo, su guion de pasos y su puntaje.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cirugias".
 */
export interface Cirugia {
  id: number;
  nombre: string;
  hueso?: (number | null) | HuesosAo;
  clasificacion?: (number | null) | ClasificacionesAo;
  tecnica?: (number | null) | TecnicasQuirurgica;
  /**
   * Se puede dejar vacío: la consola lo compone con el número del hueso y el de la clasificación. Rellénelo solo si este caso lleva uno distinto.
   */
  codigo?: string | null;
  resumen?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Archivo .glb exportado desde Blender con el hueso ya partido. Cada trozo, un objeto con nombre.
   */
  modelo?: (number | null) | Modelos3D;
  /**
   * glTF trabaja en metros, así que 1000 es lo normal. Si exportó en milímetros, ponga 1. De este número dependen todas las medidas que ve el residente.
   */
  milimetrosPorUnidad?: number | null;
  /**
   * Separa la diástasis del desplazamiento lateral: a lo largo del eje es hueco, de lado es desalineación.
   */
  ejeLargo?: ('y' | 'x' | 'z') | null;
  /**
   * Qué es cada objeto del archivo. El nombre tiene que coincidir exactamente con el del objeto en Blender.
   */
  piezas?:
    | {
        nodo: string;
        etiqueta?: string | null;
        /**
         * Piel y músculo forman las capas que se encienden y apagan. El fragmento móvil es el que se reduce. El implante empieza oculto y aparece cuando el paso lo coloca.
         */
        rol: 'piel' | 'musculo' | 'hueso' | 'fragmento' | 'implante';
        id?: string | null;
      }[]
    | null;
  /**
   * Exporte el hueso REDUCIDO, en su sitio anatómico, y describa aquí cuánto está desplazado al empezar. Así la reducción correcta es siempre volver al cero, y la consola puede medir cuánto falta.
   */
  desplazamientoInicial?: {
    x?: number | null;
    y?: number | null;
    z?: number | null;
    giroX?: number | null;
    giroY?: number | null;
    giroZ?: number | null;
  };
  pasos?:
    | {
        titulo: string;
        fase?: (number | null) | FasesQuirurgica;
        descripcion?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        objetivo: 'instrumento' | 'trazo' | 'reduccion' | 'fuerza';
        /**
         * Se exige en todos los objetivos: sin el instrumento en la mano no hay gesto.
         */
        instrumento?: (number | null) | Instrumental;
        puntos?: number | null;
        trazoMinimo?: number | null;
        trazoMaximo?: number | null;
        toleranciaDesplazamiento?: number | null;
        toleranciaDiastasis?: number | null;
        toleranciaAngulacion?: number | null;
        fuerzaMinima?: number | null;
        fuerzaMaxima?: number | null;
        /**
         * Deje la lista vacía para que se vea lo mismo que en el paso anterior. El implante aparece en el paso que lo coloca.
         */
        muestra?:
          | {
              nodo: string;
              id?: string | null;
            }[]
          | null;
        exito?: string | null;
        insuficiente?: string | null;
        excesivo?: string | null;
        riesgo?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Casos precargados. No hay modelo de inferencia: los resultados están escritos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estudios-ia".
 */
export interface EstudiosIa {
  id: number;
  nombre: string;
  codigo?: string | null;
  confianza?: number | null;
  hallazgos?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  opciones?:
    | {
        titulo: string;
        frecuente?: boolean | null;
        aFavor?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        enContra?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Agregue los bloques que necesite y arrástrelos para reordenarlos.
   */
  contenido?:
    | (
        | {
            titulo?: string | null;
            cuerpo: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            titulo?: string | null;
            puntos?:
              | {
                  destacado?: string | null;
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista-clinica';
          }
        | {
            titulo: string;
            filas?:
              | {
                  clave: string;
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabla-clasificacion';
          }
        | {
            tono: 'atencion' | 'error-frecuente' | 'perla';
            texto: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertencia';
          }
        | {
            imagen: number | Medio;
            pie?: string | null;
            ancho?: ('completo' | 'media' | 'pequena') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            video: number | Medio;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            modelo: number | Modelos3D;
            pie?: string | null;
            /**
             * Con qué ángulo y a qué distancia abre el modelo el residente.
             */
            encuadre?: {
              escala?: number | null;
              giroX?: number | null;
              giroY?: number | null;
              giroZ?: number | null;
              distanciaCamara?: number | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'modelo-3d';
          }
        | {
            /**
             * Se arman en el taller anatómico del panel.
             */
            preparacion: number | InstanciasAtlas;
            pie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instancia-atlas';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comentarios".
 */
export interface Comentario {
  id: number;
  usuario?: (number | null) | Usuario;
  coleccion: 'patologias' | 'maniobras' | 'casos-ao' | 'cirugias' | 'estudios-ia';
  documentoId: string;
  texto: string;
  estado: 'pendiente' | 'resuelto';
  updatedAt: string;
  createdAt: string;
}
/**
 * Qué ha visitado y marcado como leído cada residente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actividad".
 */
export interface Actividad {
  id: number;
  usuario: number | Usuario;
  coleccion: 'patologias' | 'maniobras' | 'casos-ao' | 'cirugias' | 'estudios-ia';
  documentoId: string;
  ultimaVisita?: string | null;
  completado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'segmentos';
        value: number | Segmento;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'modelos-3d';
        value: number | Modelos3D;
      } | null)
    | ({
        relationTo: 'instancias-atlas';
        value: number | InstanciasAtlas;
      } | null)
    | ({
        relationTo: 'huesos-ao';
        value: number | HuesosAo;
      } | null)
    | ({
        relationTo: 'clasificaciones-ao';
        value: number | ClasificacionesAo;
      } | null)
    | ({
        relationTo: 'tecnicas-quirurgicas';
        value: number | TecnicasQuirurgica;
      } | null)
    | ({
        relationTo: 'fases-quirurgicas';
        value: number | FasesQuirurgica;
      } | null)
    | ({
        relationTo: 'instrumental';
        value: number | Instrumental;
      } | null)
    | ({
        relationTo: 'patologias';
        value: number | Patologia;
      } | null)
    | ({
        relationTo: 'maniobras';
        value: number | Maniobra;
      } | null)
    | ({
        relationTo: 'casos-ao';
        value: number | CasosAo;
      } | null)
    | ({
        relationTo: 'cirugias';
        value: number | Cirugia;
      } | null)
    | ({
        relationTo: 'estudios-ia';
        value: number | EstudiosIa;
      } | null)
    | ({
        relationTo: 'comentarios';
        value: number | Comentario;
      } | null)
    | ({
        relationTo: 'actividad';
        value: number | Actividad;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  activo?: T;
  institucion?: T;
  modulosVisibles?: T;
  modulosEditables?: T;
  ultimoAcceso?: T;
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segmentos_select".
 */
export interface SegmentosSelect<T extends boolean = true> {
  nombre?: T;
  orden?: T;
  zonaMapa?:
    | T
    | {
        x?: T;
        y?: T;
        ancho?: T;
        alto?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        ancho?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-3d_select".
 */
export interface Modelos3DSelect<T extends boolean = true> {
  nombre?: T;
  origen?: T;
  anonimizado?: T;
  triangulos?: T;
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instancias-atlas_select".
 */
export interface InstanciasAtlasSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  segmento?: T;
  numeroDePiezas?: T;
  contenido?: T;
  atlasVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "huesos-ao_select".
 */
export interface HuesosAoSelect<T extends boolean = true> {
  nombre?: T;
  codigo?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clasificaciones-ao_select".
 */
export interface ClasificacionesAoSelect<T extends boolean = true> {
  codigo?: T;
  nombre?: T;
  tipo?: T;
  descripcion?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tecnicas-quirurgicas_select".
 */
export interface TecnicasQuirurgicasSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fases-quirurgicas_select".
 */
export interface FasesQuirurgicasSelect<T extends boolean = true> {
  nombre?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instrumental_select".
 */
export interface InstrumentalSelect<T extends boolean = true> {
  nombre?: T;
  icono?: T;
  descripcion?: T;
  tecnicas?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patologias_select".
 */
export interface PatologiasSelect<T extends boolean = true> {
  nombre?: T;
  subtitulo?: T;
  segmento?: T;
  codigo?: T;
  tipo?: T;
  definicion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  mecanismo?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  clasificacion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  evaluacion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  manejo?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  rehabilitacion?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  fases?:
    | T
    | {
        cuando?: T;
        titulo?: T;
        contenido?: T;
        criterio?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maniobras_select".
 */
export interface ManiobrasSelect<T extends boolean = true> {
  nombre?: T;
  segmento?: T;
  evalua?: T;
  tecnica?: T;
  positivo?: T;
  nota?: T;
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos-ao_select".
 */
export interface CasosAoSelect<T extends boolean = true> {
  titulo?: T;
  codigo?: T;
  procedimiento?: T;
  pasos?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        principio?: T;
        nota?: T;
        modelo?: T;
        id?: T;
      };
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cirugias_select".
 */
export interface CirugiasSelect<T extends boolean = true> {
  nombre?: T;
  hueso?: T;
  clasificacion?: T;
  tecnica?: T;
  codigo?: T;
  resumen?: T;
  modelo?: T;
  milimetrosPorUnidad?: T;
  ejeLargo?: T;
  piezas?:
    | T
    | {
        nodo?: T;
        etiqueta?: T;
        rol?: T;
        id?: T;
      };
  desplazamientoInicial?:
    | T
    | {
        x?: T;
        y?: T;
        z?: T;
        giroX?: T;
        giroY?: T;
        giroZ?: T;
      };
  pasos?:
    | T
    | {
        titulo?: T;
        fase?: T;
        descripcion?: T;
        objetivo?: T;
        instrumento?: T;
        puntos?: T;
        trazoMinimo?: T;
        trazoMaximo?: T;
        toleranciaDesplazamiento?: T;
        toleranciaDiastasis?: T;
        toleranciaAngulacion?: T;
        fuerzaMinima?: T;
        fuerzaMaxima?: T;
        muestra?:
          | T
          | {
              nodo?: T;
              id?: T;
            };
        exito?: T;
        insuficiente?: T;
        excesivo?: T;
        riesgo?: T;
        id?: T;
      };
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estudios-ia_select".
 */
export interface EstudiosIaSelect<T extends boolean = true> {
  nombre?: T;
  codigo?: T;
  confianza?: T;
  hallazgos?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  opciones?:
    | T
    | {
        titulo?: T;
        frecuente?: T;
        aFavor?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        enContra?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        id?: T;
      };
  contenido?:
    | T
    | {
        texto?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
              blockName?: T;
            };
        'lista-clinica'?:
          | T
          | {
              titulo?: T;
              puntos?:
                | T
                | {
                    destacado?: T;
                    texto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'tabla-clasificacion'?:
          | T
          | {
              titulo?: T;
              filas?:
                | T
                | {
                    clave?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advertencia?:
          | T
          | {
              tono?: T;
              texto?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              imagen?: T;
              pie?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
        'modelo-3d'?:
          | T
          | {
              modelo?: T;
              pie?: T;
              encuadre?:
                | T
                | {
                    escala?: T;
                    giroX?: T;
                    giroY?: T;
                    giroZ?: T;
                    distanciaCamara?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'instancia-atlas'?:
          | T
          | {
              preparacion?: T;
              pie?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comentarios_select".
 */
export interface ComentariosSelect<T extends boolean = true> {
  usuario?: T;
  coleccion?: T;
  documentoId?: T;
  texto?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actividad_select".
 */
export interface ActividadSelect<T extends boolean = true> {
  usuario?: T;
  coleccion?: T;
  documentoId?: T;
  ultimaVisita?: T;
  completado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}